modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="partialdestruction"
version="0.1.0"
displayName="Partial Destruction Prototype"
authors="VOX"
description='''
Prototype Forge 1.20.1 that replaces supported stone/TFC rock blocks with seven physical destruction stages before the final normal break.
'''

[[dependencies.partialdestruction]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.partialdestruction]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
