#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
def read(p:Path): return json.loads(p.read_text(encoding='utf-8-sig'))
def req(cond,msg):
    if not cond: raise RuntimeError(msg)
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--root',required=True);ap.add_argument('--out',required=True);ap.add_argument('--text-out',required=True);a=ap.parse_args()
    root=Path(a.root).resolve(); ev=root/'evidence/ps5/user'
    v130=read(ev/'dakar-official-psn-dlcdata-correlation-v13.0.json');v1311=read(ev/'dakar-eboot-protected-window-refinement-v13.1.1.json');v132=read(ev/'dakar-imagedigs-plaintext-pattern-census-v13.2.json');v135=read(ev/'real-v13.5-ekpfs-gate.json');v1602=read(ev/'real-v16.0.2/dakar-final-integration-v16.0.2.json');v1722=read(ev/'real-v17.2.2/dakar-pc-oracle-static-v17.2.2.json');v173=read(ev/'real-v17.3/dakar-pc-pak-playgo-correlation-v17.3.json')
    req(v130.get('remaining_unresolved_count')==3,'v13.0 residual is not 3');req(len(v130.get('remaining_unresolved_retail_hashes',[]))==3,'v13.0 residual list mismatch');req(v1311.get('eboot',{}).get('table_index')==185,'eboot table index drift');req(v1311.get('eboot',{}).get('chunk_id')==0,'eboot chunk drift');req(v135.get('gate_state')=='WAITING_FOR_SUPPLIED_EKPFS','historical EKPFS gate drift');req(v1602.get('status')=='PENDING','v16.0.2 final state drift');req(v173.get('exact_new_match_count')==0,'v17.3 real correlation unexpectedly changed')
    pc_paks=int(v1722.get('pak_count',0));pc_imports=len((v1722.get('shipping_exe') or {}).get('imports') or []);unresolved=[{'table_index':int(x['table_index']),'chunk_id':int(x['chunk_id']),'hash_hex':str(x['hash_hex'])} for x in v130['remaining_unresolved_retail_hashes']]
    rep={'schema':'ps5native.canonical-state.v18.0','status':'READY','validated_baseline_percent':86.0,'target_percent':100.0,'roadmap_credit':0.0,'canonical':{'playgo_retail_entries':int(v130.get('baseline_retail_hash_count',191)),'playgo_named_entries':int(v130.get('total_named_count',188)),'playgo_unresolved_count':3,'playgo_unresolved':unresolved,'eboot_table_index':185,'eboot_chunk_id':0,'eboot_path_hash':str(v1311['eboot']['hash_hex']),'chunk0_pfs_image_overlap_bytes':int(v1311.get('eboot_chunk0_pfs_image_overlap_after_bytes',0)),'imagedigs_digest_count':int((v132.get('imagedigs_entry') or {}).get('digest_count',0)),'pfs_image_block_count':int(v132.get('pfs_image_block_count',0)),'historical_key_gate_state':str(v135.get('gate_state')),'historical_final_integration_status':str(v1602.get('status')),'historical_final_integration_blocker':str(v1602.get('blocker')),'pc_static_oracle_pak_count':pc_paks,'pc_static_oracle_import_count':pc_imports,'v17_3_exact_hash_matches':int(v173.get('exact_new_match_count',0))},'execution_frontier':{'last_validated_stage':'PUBLIC_RETAIL_METADATA_AND_OUTER_PFS_GEOMETRY','first_blocked_stage':'VALIDATED_EKPFS_GATE','first_blocked_operation':'Decrypt and authenticate the first required retail outer-PFS data block using a supplied EKPFS validated against imagedigs.','downstream_not_yet_reached':['NAPS/FIDX decode','exact eboot logical range recovery','eboot plaintext extraction','retail module-set closure','relocation/entry preflight','real Dakar guest entry','visible menu/gameplay']},'pc_oracle_boundary':{'runtime_dependency_allowed':False,'payload_copy_allowed':False,'pc_executable_launch_allowed':False},'contradictions_removed':['v17.3 stale 18-unresolved target set; canonical residue is 3 from v13.0']}
    Path(a.out).write_text(json.dumps(rep,indent=2)+'\n',encoding='utf-8');Path(a.text_out).write_text('READY\n',encoding='utf-8');print('V180_CANONICAL_RECONCILIATION_OK');return 0
if __name__=='__main__': raise SystemExit(main())
